/**
 * config-keys.ts
 * 所有环境变量 KEY 集中声明，类型安全、自动补全，便于前后端一致维护
 * 
 * - 所有前端可见变量统一加 NEXT_PUBLIC_ 前缀
 * - 新增变量需同步到 .env.example、config-keys.ts、config-types.ts、环境变量文档
 * - 建议所有配置项通过配置服务统一访问，避免魔法字符串
 */

// 数据库/ORM 相关
export const DB_KEYS = {
  NEXT_PUBLIC_DB_URL: 'NEXT_PUBLIC_DB_URL',
  // 废弃：NEXT_PUBLIC_DATABASE_PROVIDER、NEXT_PUBLIC_ONLINE_DB、NEXT_PUBLIC_OFFLINE_DB、NEXT_PUBLIC_OFFLINE_DB_TYPE、NEXT_PUBLIC_MOCK_DB_MODE、NEXT_PUBLIC_MOCK_SQLITE_FILE
  // 新推荐变量：
  NEXT_PUBLIC_ONLINE_DB_PROVIDER: 'NEXT_PUBLIC_ONLINE_DB_PROVIDER',
  NEXT_PUBLIC_OFFLINE_DB_PROVIDER: 'NEXT_PUBLIC_OFFLINE_DB_PROVIDER',
  NEXT_PUBLIC_DB_ORM: 'NEXT_PUBLIC_DB_ORM',
  NEXT_PUBLIC_CACHE_PROVIDER: 'NEXT_PUBLIC_CACHE_PROVIDER',
  // [已彻底废弃] 
  // NEXT_PUBLIC_MOCK_DB_MODE: 'NEXT_PUBLIC_MOCK_DB_MODE', 
  // NEXT_PUBLIC_MOCK_SQLITE_FILE: 'NEXT_PUBLIC_MOCK_SQLITE_FILE', 
};

// 认证/服务类型相关
export const AUTH_KEYS = {
  NEXT_PUBLIC_AUTH_STRATEGY: 'NEXT_PUBLIC_AUTH_STRATEGY',
  NEXT_PUBLIC_AUTH_PROVIDER: 'NEXT_PUBLIC_AUTH_PROVIDER',
  NEXT_PUBLIC_SOCIAL_LOGIN_PROVIDERS: 'NEXT_PUBLIC_SOCIAL_LOGIN_PROVIDERS',
  NEXT_PUBLIC_USER_SERVICE_TYPE: 'NEXT_PUBLIC_USER_SERVICE_TYPE',
  NEXT_PUBLIC_MESSAGE_SERVICE_TYPE: 'NEXT_PUBLIC_MESSAGE_SERVICE_TYPE',
  NEXT_PUBLIC_NOTIFICATION_SERVICE_TYPE: 'NEXT_PUBLIC_NOTIFICATION_SERVICE_TYPE',
  NEXT_PUBLIC_PAYMENT_SERVICE_TYPE: 'NEXT_PUBLIC_PAYMENT_SERVICE_TYPE',
  NEXT_PUBLIC_QUIZ_SERVICE_TYPE: 'NEXT_PUBLIC_QUIZ_SERVICE_TYPE',
  NEXT_PUBLIC_BETTER_AUTH_API_URL: 'NEXT_PUBLIC_BETTER_AUTH_API_URL',
  BETTER_AUTH_SECRET: 'BETTER_AUTH_SECRET',
  // 社交登录配置
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: 'NEXT_PUBLIC_GOOGLE_CLIENT_ID',
  NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: 'NEXT_PUBLIC_GOOGLE_CLIENT_SECRET',
  NEXT_PUBLIC_FACEBOOK_APP_ID: 'NEXT_PUBLIC_FACEBOOK_APP_ID',
  NEXT_PUBLIC_FACEBOOK_APP_SECRET: 'NEXT_PUBLIC_FACEBOOK_APP_SECRET',
  NEXT_PUBLIC_APPLE_TEAM_ID: 'NEXT_PUBLIC_APPLE_TEAM_ID',
  NEXT_PUBLIC_APPLE_KEY_ID: 'NEXT_PUBLIC_APPLE_KEY_ID',
  NEXT_PUBLIC_APPLE_PRIVATE_KEY: 'NEXT_PUBLIC_APPLE_PRIVATE_KEY',
  // 会话配置
  NEXT_PUBLIC_SESSION_DURATION: 'NEXT_PUBLIC_SESSION_DURATION',
  NEXT_PUBLIC_SESSION_REFRESH: 'NEXT_PUBLIC_SESSION_REFRESH',
  NEXT_PUBLIC_SESSION_COOKIE_NAME: 'NEXT_PUBLIC_SESSION_COOKIE_NAME',
  NEXT_PUBLIC_SESSION_COOKIE_DOMAIN: 'NEXT_PUBLIC_SESSION_COOKIE_DOMAIN',
  NEXT_PUBLIC_SESSION_COOKIE_SECURE: 'NEXT_PUBLIC_SESSION_COOKIE_SECURE',
  // token 配置
  NEXT_PUBLIC_TOKEN_EXPIRY: 'NEXT_PUBLIC_TOKEN_EXPIRY',
  NEXT_PUBLIC_TOKEN_REFRESH: 'NEXT_PUBLIC_TOKEN_REFRESH',
  NEXT_PUBLIC_TOKEN_ALGORITHM: 'NEXT_PUBLIC_TOKEN_ALGORITHM',
  NEXT_PUBLIC_TOKEN_SECRET: 'NEXT_PUBLIC_TOKEN_SECRET',
  // 安全配置
  NEXT_PUBLIC_AUTH_RATE_LIMIT: 'NEXT_PUBLIC_AUTH_RATE_LIMIT',
  NEXT_PUBLIC_LOGIN_ATTEMPTS: 'NEXT_PUBLIC_LOGIN_ATTEMPTS',
  NEXT_PUBLIC_LOCKOUT_DURATION: 'NEXT_PUBLIC_LOCKOUT_DURATION',
  NEXT_PUBLIC_PASSWORD_MIN_LENGTH: 'NEXT_PUBLIC_PASSWORD_MIN_LENGTH',
  NEXT_PUBLIC_PASSWORD_MAX_LENGTH: 'NEXT_PUBLIC_PASSWORD_MAX_LENGTH',
  NEXT_PUBLIC_PASSWORD_REQUIRE_UPPERCASE: 'NEXT_PUBLIC_PASSWORD_REQUIRE_UPPERCASE',
  NEXT_PUBLIC_PASSWORD_REQUIRE_LOWERCASE: 'NEXT_PUBLIC_PASSWORD_REQUIRE_LOWERCASE',
  NEXT_PUBLIC_PASSWORD_REQUIRE_NUMBER: 'NEXT_PUBLIC_PASSWORD_REQUIRE_NUMBER',
  NEXT_PUBLIC_PASSWORD_REQUIRE_SPECIAL: 'NEXT_PUBLIC_PASSWORD_REQUIRE_SPECIAL',
  NEXT_PUBLIC_CORS_ORIGINS: 'NEXT_PUBLIC_CORS_ORIGINS',
  NEXT_PUBLIC_CORS_METHODS: 'NEXT_PUBLIC_CORS_METHODS',
  NEXT_PUBLIC_CORS_HEADERS: 'NEXT_PUBLIC_CORS_HEADERS',
  NEXT_PUBLIC_XSS_PROTECTION: 'NEXT_PUBLIC_XSS_PROTECTION',
  NEXT_PUBLIC_CONTENT_SECURITY_POLICY: 'NEXT_PUBLIC_CONTENT_SECURITY_POLICY',
};

// 云存储（Firebase等）相关
export const STORAGE_KEYS = {
  NEXT_PUBLIC_FIREBASE_API_KEY: 'NEXT_PUBLIC_FIREBASE_API_KEY',
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  NEXT_PUBLIC_FIREBASE_APP_ID: 'NEXT_PUBLIC_FIREBASE_APP_ID',
};

// 推送服务相关
export const PUSH_KEYS = {
  NEXT_PUBLIC_PUSH_APP_KEY: 'NEXT_PUBLIC_PUSH_APP_KEY',
};

// 通用/辅助配置
export const GENERAL_KEYS = {
  NEXT_PUBLIC_NODE_ENV: 'NEXT_PUBLIC_NODE_ENV',
  NEXT_PUBLIC_ENV_STAGE: 'NEXT_PUBLIC_ENV_STAGE',
  NEXT_PUBLIC_DATA_MODE: 'NEXT_PUBLIC_DATA_MODE',
  NEXT_PUBLIC_API_BASE_URL: 'NEXT_PUBLIC_API_BASE_URL',
  NEXT_PUBLIC_API_ENV: 'NEXT_PUBLIC_API_ENV',
  NEXT_PUBLIC_PLATFORM: 'NEXT_PUBLIC_PLATFORM',
  NEXT_PUBLIC_LOG_LEVEL: 'NEXT_PUBLIC_LOG_LEVEL',
  NEXT_PUBLIC_PROVIDER_TYPE: 'NEXT_PUBLIC_PROVIDER_TYPE',
  NEXT_PUBLIC_FEATURE_FLAG: 'NEXT_PUBLIC_FEATURE_FLAG',
  NEXT_PUBLIC_BRAND: 'NEXT_PUBLIC_BRAND',
  NEXT_PUBLIC_SYNC_AUTO_ON_CONNECT: 'NEXT_PUBLIC_SYNC_AUTO_ON_CONNECT',
  NEXT_PUBLIC_SYNC_INTERVAL: 'NEXT_PUBLIC_SYNC_INTERVAL',
  NEXT_PUBLIC_SYNC_ENABLED: 'NEXT_PUBLIC_SYNC_ENABLED',
  NEXT_PUBLIC_SYNC_STRATEGY: 'NEXT_PUBLIC_SYNC_STRATEGY',
  NEXT_PUBLIC_SYNC_CONFLICT_RESOLUTION: 'NEXT_PUBLIC_SYNC_CONFLICT_RESOLUTION',
  NEXT_PUBLIC_ENABLE_OFFLINE: 'NEXT_PUBLIC_ENABLE_OFFLINE',
  NEXT_PUBLIC_ENABLE_HYBRID: 'NEXT_PUBLIC_ENABLE_HYBRID',
  NEXT_PUBLIC_CONFLICT_RESOLUTION: 'NEXT_PUBLIC_CONFLICT_RESOLUTION',
  NEXT_PUBLIC_LOAD_TEST_DATA: 'NEXT_PUBLIC_LOAD_TEST_DATA',
  NEXT_PUBLIC_TEST_DATA_SOURCE: 'NEXT_PUBLIC_TEST_DATA_SOURCE',
  NEXT_PUBLIC_QUIZ_API_BASE_URL: 'NEXT_PUBLIC_QUIZ_API_BASE_URL',
  NEXT_PUBLIC_QUIZ_AI_BASE_URL: 'NEXT_PUBLIC_QUIZ_AI_BASE_URL',
  NEXT_PUBLIC_APP_VERSION: 'NEXT_PUBLIC_APP_VERSION',
  NEXT_PUBLIC_BUILD_NUMBER: 'NEXT_PUBLIC_BUILD_NUMBER',
  NEXT_PUBLIC_USE_MOCK_NETWORK: 'NEXT_PUBLIC_USE_MOCK_NETWORK',
  NEXT_PUBLIC_USE_MOCK_DB: 'NEXT_PUBLIC_USE_MOCK_DB',
  LOGGER_PROVIDER: 'LOGGER_PROVIDER',
  LOG_LEVEL: 'LOG_LEVEL',
  EMAIL_PROVIDER: 'EMAIL_PROVIDER',
  R2_REGION: 'R2_REGION',
  R2_ENDPOINT: 'R2_ENDPOINT',
  R2_ACCESS_KEY_ID: 'R2_ACCESS_KEY_ID',
  R2_SECRET_ACCESS_KEY: 'R2_SECRET_ACCESS_KEY',
  R2_BUCKET: 'R2_BUCKET',
  R2_PUBLIC_BASE_URL: 'R2_PUBLIC_BASE_URL',
  GITHUB_TOKEN: 'GITHUB_TOKEN',
  GITHUB_REPO: 'GITHUB_REPO',
  GITHUB_BRANCH: 'GITHUB_BRANCH',
  GITHUB_PATH: 'GITHUB_PATH',
  GITHUB_RAW_BASE: 'GITHUB_RAW_BASE',
  TG_BOT_TOKEN: 'TG_BOT_TOKEN',
  TG_CHAT_ID: 'TG_CHAT_ID',
  CACHE_STRATEGY: 'CACHE_STRATEGY',
  OFFLINE_FALLBACK: 'OFFLINE_FALLBACK',
  EXPIRY_STRATEGY: 'EXPIRY_STRATEGY',
  SYNC_ENTITY_TYPES: 'SYNC_ENTITY_TYPES', // 需同步的表名，逗号分隔
};

// email 相关
export const EMAIL_KEYS = {
  EMAIL_PROVIDER: 'EMAIL_PROVIDER', // 后端/Node 环境变量
  NEXT_PUBLIC_EMAIL_PROVIDER: 'NEXT_PUBLIC_EMAIL_PROVIDER', // 前端 provider
};

// 配置中心相关
export const CONFIG_CENTER_KEYS = {
  NEXT_PUBLIC_CONFIG_WS_URL: 'NEXT_PUBLIC_CONFIG_WS_URL',
  NEXT_PUBLIC_CONFIG_SSE_URL: 'NEXT_PUBLIC_CONFIG_SSE_URL',
  NEXT_PUBLIC_CONFIG_CONSUL_URL: 'NEXT_PUBLIC_CONFIG_CONSUL_URL',
};

// network 相关
export const NETWORK_KEYS = {
  NEXT_PUBLIC_NETWORK_PROVIDER: 'NEXT_PUBLIC_NETWORK_PROVIDER', // 推荐前端 provider
  NETWORK_PROVIDER: 'NETWORK_PROVIDER', // 后端/Node 环境变量
};

// 数据初始化相关
export const DB_INIT_KEYS = {
  NEXT_PUBLIC_DB_INIT_MODE: 'NEXT_PUBLIC_DB_INIT_MODE', // schema/json/memory/sql
  NEXT_PUBLIC_DB_INIT_SOURCE: 'NEXT_PUBLIC_DB_INIT_SOURCE', // ./mock-data.json、./mock-sql、memory、remote
  NEXT_PUBLIC_DB_INIT_LOAD_DEFAULT: 'NEXT_PUBLIC_DB_INIT_LOAD_DEFAULT', // true/false
  NEXT_PUBLIC_DB_INIT_TABLES: 'NEXT_PUBLIC_DB_INIT_TABLES', // users,settings,... 可选
};

// 配置服务 provider 类型（枚举，已迁移至 common.ts）
export { ConfigProviderType } from '@/core/lib/db/types/common';

// 业务服务相关配置键
export const BUSINESS_KEYS = {
  // 消息服务
  NEXT_PUBLIC_MESSAGE_TYPE: 'NEXT_PUBLIC_MESSAGE_TYPE',
  NEXT_PUBLIC_MESSAGE_FEATURES: 'NEXT_PUBLIC_MESSAGE_FEATURES',
  NEXT_PUBLIC_MESSAGE_ADAPTERS: 'NEXT_PUBLIC_MESSAGE_ADAPTERS',
  MESSAGE_REPOSITORY_MAP: 'MESSAGE_REPOSITORY_MAP',
  
  // 测验服务
  NEXT_PUBLIC_QUIZ_TYPE: 'NEXT_PUBLIC_QUIZ_TYPE',
  NEXT_PUBLIC_QUIZ_FEATURES: 'NEXT_PUBLIC_QUIZ_FEATURES',
  QUIZ_ADAPTER_MAP: 'QUIZ_ADAPTER_MAP',
  
  // 匹配服务
  NEXT_PUBLIC_MATCH_TYPE: 'NEXT_PUBLIC_MATCH_TYPE',
  NEXT_PUBLIC_MATCH_ENHANCER_LIST: 'NEXT_PUBLIC_MATCH_ENHANCER_LIST',
  MATCH_ENHANCER_LIST: 'MATCH_ENHANCER_LIST',
  DATA_SERVICE: 'DATA_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  SETTING_SERVICE: 'SETTING_SERVICE',
  
  // 引导服务
  NEXT_PUBLIC_ONBOARD_TYPE: 'NEXT_PUBLIC_ONBOARD_TYPE',
  NEXT_PUBLIC_ONBOARD_FEATURES: 'NEXT_PUBLIC_ONBOARD_FEATURES',
  ONBOARD_ADAPTER_MAP: 'ONBOARD_ADAPTER_MAP',
  ONBOARD_TYPE: 'ONBOARD_TYPE',
  ONBOARD_FEATURES: 'ONBOARD_FEATURES',
  ONBOARD_OPTIONS: 'ONBOARD_OPTIONS',
};

// 已废弃对象写法，仅兼容保留（如无使用可删除）
// export const CONFIG_PROVIDER_TYPES = {
//   ENV: 'env',
//   MOCK: 'mock',
//   REMOTE: 'remote',
//   DEFAULT: 'default',
//   // 可扩展 localfile/consul/etcd/ssm
// } as const;
//
// export type ConfigProviderTypeKey = keyof typeof CONFIG_PROVIDER_TYPES;
// export type ConfigProviderTypeValue = typeof CONFIG_PROVIDER_TYPES[ConfigProviderTypeKey];

import type { ConfigSchema } from './config-types';

// 合并导出
export const CONFIG_KEYS = {
  ...DB_KEYS,
  ...AUTH_KEYS,
  ...STORAGE_KEYS,
  ...PUSH_KEYS,
  ...GENERAL_KEYS,
  ...NETWORK_KEYS,
  ...EMAIL_KEYS,
  ...CONFIG_CENTER_KEYS,
  ...DB_INIT_KEYS,
  ...BUSINESS_KEYS, // 新增业务服务相关配置键
  NEXT_PUBLIC_ENTITY_TYPES: 'NEXT_PUBLIC_ENTITY_TYPES',
};

// 类型导出，便于类型安全访问
export type ConfigKey = keyof typeof CONFIG_KEYS;

// 合并导出
