// config-keys.ts
// 分组集中声明所有环境变量 KEY，便于前后端一致、类型推断与自动补全

// 数据库/ORM 相关
export const DB_KEYS = {
  NEXT_PUBLIC_DB_URL: 'NEXT_PUBLIC_DB_URL',
  NEXT_PUBLIC_DATABASE_ENV: 'NEXT_PUBLIC_DATABASE_ENV',
  NEXT_PUBLIC_MOCK_DB_MODE: 'NEXT_PUBLIC_MOCK_DB_MODE',
  NEXT_PUBLIC_ONLINE_DB: 'NEXT_PUBLIC_ONLINE_DB',
  NEXT_PUBLIC_OFFLINE_DB: 'NEXT_PUBLIC_OFFLINE_DB',
  NEXT_PUBLIC_MOCK_SQLITE_FILE: 'NEXT_PUBLIC_MOCK_SQLITE_FILE',
};

// 认证服务相关
export const AUTH_KEYS = {
  NEXT_PUBLIC_AUTH_TYPE: 'NEXT_PUBLIC_AUTH_TYPE',
  NEXT_PUBLIC_AUTH_SERVICE_TYPE: 'NEXT_PUBLIC_AUTH_SERVICE_TYPE',
  NEXT_PUBLIC_BETTER_AUTH_API_URL: 'NEXT_PUBLIC_BETTER_AUTH_API_URL',
  BETTER_AUTH_SECRET: 'BETTER_AUTH_SECRET',
};

// 云存储（Firebase等）相关
export const STORAGE_KEYS = {
  NEXT_PUBLIC_FIREBASE_API_KEY: 'NEXT_PUBLIC_FIREBASE_API_KEY',
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  NEXT_PUBLIC_FIREBASE_APP_ID: 'NEXT_PUBLIC_FIREBASE_APP_ID',
};

// 推送服务相关（如有可补充）
export const PUSH_KEYS = {
  // NEXT_PUBLIC_PUSH_APP_KEY: 'NEXT_PUBLIC_PUSH_APP_KEY',
};

// 通用/辅助配置
export const GENERAL_KEYS = {
  NEXT_PUBLIC_NODE_ENV: 'NEXT_PUBLIC_NODE_ENV',
  NEXT_PUBLIC_ENV_STAGE: 'NEXT_PUBLIC_ENV_STAGE',
  NEXT_PUBLIC_DATA_MODE: 'NEXT_PUBLIC_DATA_MODE',
  NEXT_PUBLIC_LOG_LEVEL: 'NEXT_PUBLIC_LOG_LEVEL',
  NEXT_PUBLIC_PROVIDER_TYPE: 'NEXT_PUBLIC_PROVIDER_TYPE',
  NEXT_PUBLIC_FEATURE_FLAG: 'NEXT_PUBLIC_FEATURE_FLAG',
  NEXT_PUBLIC_BRAND: 'NEXT_PUBLIC_BRAND',
  NEXT_PUBLIC_SYNC_AUTO_ON_CONNECT: 'NEXT_PUBLIC_SYNC_AUTO_ON_CONNECT',
  NEXT_PUBLIC_SYNC_INTERVAL: 'NEXT_PUBLIC_SYNC_INTERVAL',
  NEXT_PUBLIC_SYNC_CONFLICT_RESOLUTION: 'NEXT_PUBLIC_SYNC_CONFLICT_RESOLUTION',
  NEXT_PUBLIC_ENABLE_OFFLINE: 'NEXT_PUBLIC_ENABLE_OFFLINE',
  NEXT_PUBLIC_ENABLE_HYBRID: 'NEXT_PUBLIC_ENABLE_HYBRID',
  NEXT_PUBLIC_LOAD_TEST_DATA: 'NEXT_PUBLIC_LOAD_TEST_DATA',
  NEXT_PUBLIC_TEST_DATA_SOURCE: 'NEXT_PUBLIC_TEST_DATA_SOURCE',
  NEXT_PUBLIC_API_BASE_URL: 'NEXT_PUBLIC_API_BASE_URL',
  LOGGER_PROVIDER: 'LOGGER_PROVIDER', 
};

// 合并导出
export const CONFIG_KEYS = {
  ...DB_KEYS,
  ...AUTH_KEYS,
  ...STORAGE_KEYS,
  ...PUSH_KEYS,
  ...GENERAL_KEYS,
};

export type ConfigKey = keyof typeof CONFIG_KEYS;
