const nextJest = require('next/jest');

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
});

// Add any custom config to be passed to Jest
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testEnvironment: 'jest-environment-jsdom',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@db/(.*)$': '<rootDir>/src/core/lib/db/$1',
    '^@db/types/(.*)$': '<rootDir>/src/core/lib/db/types/$1',
    '^@db/interfaces/(.*)$': '<rootDir>/src/core/lib/db/interfaces/$1',
    '^@db/test/(.*)$': '<rootDir>/src/core/lib/db/test/$1',
  },
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/.next/'],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
  },
  transformIgnorePatterns: [
    '/node_modules/',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/*.stories.{js,jsx,ts,tsx}',
    '!src/**/*.test.{js,jsx,ts,tsx}',
    '!src/**/*.spec.{js,jsx,ts,tsx}',
    '!src/**/index.{js,jsx,ts,tsx}',
    '!src/**/types.{js,jsx,ts,tsx}',
    '!src/**/constants.{js,jsx,ts,tsx}',
    '!src/**/styles.{js,jsx,ts,tsx}',
    '!src/**/theme.{js,jsx,ts,tsx}',
    '!src/**/config.{js,jsx,ts,tsx}',
    '!src/**/setupTests.{js,jsx,ts,tsx}',
    '!src/**/jest.setup.{js,jsx,ts,tsx}',
    '!src/**/jest.config.{js,jsx,ts,tsx}',
    '!src/**/next.config.{js,jsx,ts,tsx}',
    '!src/**/postcss.config.{js,jsx,ts,tsx}',
    '!src/**/tailwind.config.{js,jsx,ts,tsx}',
    '!src/**/babel.config.{js,jsx,ts,tsx}',
    '!src/**/webpack.config.{js,jsx,ts,tsx}',
    '!src/**/tsconfig.{js,jsx,ts,tsx}',
    '!src/**/eslintrc.{js,jsx,ts,tsx}',
    '!src/**/prettierrc.{js,jsx,ts,tsx}',
    '!src/**/stylelintrc.{js,jsx,ts,tsx}',
    '!src/**/commitlintrc.{js,jsx,ts,tsx}',
    '!src/**/huskyrc.{js,jsx,ts,tsx}',
    '!src/**/lintstagedrc.{js,jsx,ts,tsx}',
    '!src/**/nodemonrc.{js,jsx,ts,tsx}',
    '!src/**/pm2rc.{js,jsx,ts,tsx}',
    '!src/**/dockerfile',
    '!src/**/docker-compose.yml',
    '!src/**/README.md',
    '!src/**/CHANGELOG.md',
    '!src/**/LICENSE',
    '!src/**/.gitignore',
    '!src/**/.npmignore',
    '!src/**/.eslintignore',
    '!src/**/.prettierignore',
    '!src/**/.stylelintignore',
    '!src/**/.commitlintignore',
    '!src/**/.huskyignore',
    '!src/**/.lintstagedignore',
    '!src/**/.nodemonignore',
    '!src/**/.pm2ignore',
    '!src/**/.dockerignore',
    '!src/**/.gitattributes',
    '!src/**/.gitmodules',
    '!src/**/.gitkeep',
    '!src/**/.keep',
    '!src/**/.DS_Store',
    '!src/**/Thumbs.db',
    '!src/**/desktop.ini',
    '!src/**/package-lock.json',
    '!src/**/yarn.lock',
    '!src/**/pnpm-lock.yaml',
    '!src/**/bun.lockb',
    '!src/**/node_modules/**',
    '!src/**/.next/**',
    '!src/**/out/**',
    '!src/**/dist/**',
    '!src/**/build/**',
    '!src/**/coverage/**',
    '!src/**/.nyc_output/**',
    '!src/**/.vercel/**',
    '!src/**/.netlify/**',
    '!src/**/.github/**',
    '!src/**/.git/**',
    '!src/**/.vscode/**',
    '!src/**/.idea/**',
    '!src/**/.cache/**',
    '!src/**/.temp/**',
    '!src/**/.env*',
    '!src/**/.env.*',
    '!src/**/.env.*.local',
    '!src/**/.env.local',
    '!src/**/.env.development',
    '!src/**/.env.test',
    '!src/**/.env.production',
    '!src/**/.env.mock',
    '!src/**/.env.example',
    '!src/**/.env.template',
    '!src/**/.env.sample',
    '!src/**/.env.default',
    '!src/**/.env.dist',
    '!src/**/.env.dev',
    '!src/**/.env.prod',
    '!src/**/.env.stage',
    '!src/**/.env.qa',
    '!src/**/.env.uat',
    '!src/**/.env.preview',
    '!src/**/.env.review',
    '!src/**/.env.release',
    '!src/**/.env.beta',
    '!src/**/.env.alpha',
    '!src/**/.env.canary',
    '!src/**/.env.nightly',
    '!src/**/.env.ci',
    '!src/**/.env.cd',
    '!src/**/.env.deploy',
    '!src/**/.env.build',
    '!src/**/.env.package',
    '!src/**/.env.publish',
    '!src/**/.env.release',
    '!src/**/.env.version',
    '!src/**/.env.tag',
    '!src/**/.env.branch',
    '!src/**/.env.commit',
    '!src/**/.env.hash',
    '!src/**/.env.date',
    '!src/**/.env.time',
    '!src/**/.env.timestamp',
    '!src/**/.env.epoch',
    '!src/**/.env.random',
    '!src/**/.env.uuid',
    '!src/**/.env.guid',
    '!src/**/.env.secret',
    '!src/**/.env.key',
    '!src/**/.env.token',
    '!src/**/.env.password',
    '!src/**/.env.credential',
    '!src/**/.env.credential.*',
    '!src/**/.env.credential.*.local',
    '!src/**/.env.credential.local',
    '!src/**/.env.credential.development',
    '!src/**/.env.credential.test',
    '!src/**/.env.credential.production',
    '!src/**/.env.credential.mock',
    '!src/**/.env.credential.example',
    '!src/**/.env.credential.template',
    '!src/**/.env.credential.sample',
    '!src/**/.env.credential.default',
    '!src/**/.env.credential.dist',
    '!src/**/.env.credential.dev',
    '!src/**/.env.credential.prod',
    '!src/**/.env.credential.stage',
    '!src/**/.env.credential.qa',
    '!src/**/.env.credential.uat',
    '!src/**/.env.credential.preview',
    '!src/**/.env.credential.review',
    '!src/**/.env.credential.release',
    '!src/**/.env.credential.beta',
    '!src/**/.env.credential.alpha',
    '!src/**/.env.credential.canary',
    '!src/**/.env.credential.nightly',
    '!src/**/.env.credential.ci',
    '!src/**/.env.credential.cd',
    '!src/**/.env.credential.deploy',
    '!src/**/.env.credential.build',
    '!src/**/.env.credential.package',
    '!src/**/.env.credential.publish',
    '!src/**/.env.credential.release',
    '!src/**/.env.credential.version',
    '!src/**/.env.credential.tag',
    '!src/**/.env.credential.branch',
    '!src/**/.env.credential.commit',
    '!src/**/.env.credential.hash',
    '!src/**/.env.credential.date',
    '!src/**/.env.credential.time',
    '!src/**/.env.credential.timestamp',
    '!src/**/.env.credential.epoch',
    '!src/**/.env.credential.random',
    '!src/**/.env.credential.uuid',
    '!src/**/.env.credential.guid',
    '!src/**/.env.credential.secret',
    '!src/**/.env.credential.key',
    '!src/**/.env.credential.token',
    '!src/**/.env.credential.password',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
    '<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}',
  ],
  testEnvironment: 'jsdom',
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx', 'json', 'node'],
  moduleDirectories: ['node_modules', 'src'],
  modulePaths: ['<rootDir>/src'],
  resetMocks: true,
  restoreMocks: true,
  clearMocks: true,
  resetModules: true,
  verbose: true,
  bail: false,
  cache: true,
  cacheDirectory: '<rootDir>/.jest-cache',
  collectCoverage: true,
  coverageDirectory: '<rootDir>/coverage',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/.next/',
    '/out/',
    '/dist/',
    '/build/',
    '/coverage/',
    '/.nyc_output/',
    '/.vercel/',
    '/.netlify/',
    '/.github/',
    '/.git/',
    '/.vscode/',
    '/.idea/',
    '/.cache/',
    '/.temp/',
    '/.env*/',
    '/.env.*/',
    '/.env.*.local/',
    '/.env.local/',
    '/.env.development/',
    '/.env.test/',
    '/.env.production/',
    '/.env.mock/',
    '/.env.example/',
    '/.env.template/',
    '/.env.sample/',
    '/.env.default/',
    '/.env.dist/',
    '/.env.dev/',
    '/.env.prod/',
    '/.env.stage/',
    '/.env.qa/',
    '/.env.uat/',
    '/.env.preview/',
    '/.env.review/',
    '/.env.release/',
    '/.env.beta/',
    '/.env.alpha/',
    '/.env.canary/',
    '/.env.nightly/',
    '/.env.ci/',
    '/.env.cd/',
    '/.env.deploy/',
    '/.env.build/',
    '/.env.package/',
    '/.env.publish/',
    '/.env.release/',
    '/.env.version/',
    '/.env.tag/',
    '/.env.branch/',
    '/.env.commit/',
    '/.env.hash/',
    '/.env.date/',
    '/.env.time/',
    '/.env.timestamp/',
    '/.env.epoch/',
    '/.env.random/',
    '/.env.uuid/',
    '/.env.guid/',
    '/.env.secret/',
    '/.env.key/',
    '/.env.token/',
    '/.env.password/',
    '/.env.credential*/',
    '/.env.credential.*/',
    '/.env.credential.*.local/',
    '/.env.credential.local/',
    '/.env.credential.development/',
    '/.env.credential.test/',
    '/.env.credential.production/',
    '/.env.credential.mock/',
    '/.env.credential.example/',
    '/.env.credential.template/',
    '/.env.credential.sample/',
    '/.env.credential.default/',
    '/.env.credential.dist/',
    '/.env.credential.dev/',
    '/.env.credential.prod/',
    '/.env.credential.stage/',
    '/.env.credential.qa/',
    '/.env.credential.uat/',
    '/.env.credential.preview/',
    '/.env.credential.review/',
    '/.env.credential.release/',
    '/.env.credential.beta/',
    '/.env.credential.alpha/',
    '/.env.credential.canary/',
    '/.env.credential.nightly/',
    '/.env.credential.ci/',
    '/.env.credential.cd/',
    '/.env.credential.deploy/',
    '/.env.credential.build/',
    '/.env.credential.package/',
    '/.env.credential.publish/',
    '/.env.credential.release/',
    '/.env.credential.version/',
    '/.env.credential.tag/',
    '/.env.credential.branch/',
    '/.env.credential.commit/',
    '/.env.credential.hash/',
    '/.env.credential.date/',
    '/.env.credential.time/',
    '/.env.credential.timestamp/',
    '/.env.credential.epoch/',
    '/.env.credential.random/',
    '/.env.credential.uuid/',
    '/.env.credential.guid/',
    '/.env.credential.secret/',
    '/.env.credential.key/',
    '/.env.credential.token/',
    '/.env.credential.password/',
  ],
  coverageReporters: ['text', 'lcov', 'clover', 'html', 'json', 'json-summary'],
  coverageProvider: 'v8',
  reporters: ['default', 'jest-junit'],
  testResultsProcessor: 'jest-junit',
  testRunner: 'jest-circus/runner',
  testSequencer: '@jest/test-sequencer',
  testTimeout: 10000,
  maxWorkers: '50%',
  maxConcurrency: 5,
  globals: {
    'ts-jest': {
      tsconfig: 'tsconfig.jest.json',
    },
  },
};

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
module.exports = createJestConfig(customJestConfig); 