'use client';

import React, { useState, useEffect, useRef } from 'react';
import { IonButton, IonCard, IonCardContent, IonCardHeader, IonCardTitle, IonContent, IonItem, IonLabel, IonList } from '@ionic/react';
import { CapacitorSQLiteClient } from '@/core/lib/db/clients/capacitor-sqlite/capacitor-sqlite-client';

// Define a simple user type
interface User {
  id: string;
  name: string;
  email: string;
  age: number;
}

export default function SQLiteDemo() {
  const [log, setLog] = useState<string[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [isDbInitialized, setIsDbInitialized] = useState(false);
  const dbClientRef = useRef<CapacitorSQLiteClient | null>(null);
  const tableName = 'users';

  // Initialize the database
  useEffect(() => {
    const initDatabase = async () => {
      try {
        // Create a new SQLite client
        const dbClient = new CapacitorSQLiteClient({
          name: 'demo-database',
          version: 1,
          engine: 'sqlite' // 添加必需的 engine 属性
        });

        // Initialize the database
        await dbClient.initialize();
        dbClientRef.current = dbClient;
        setIsDbInitialized(true);
        
        // Create users table if it doesn't exist
        await createUsersTable();
        
        addLog('数据库初始化成功');
      } catch (error) {
        addLog(`数据库初始化失败: ${error instanceof Error ? error.message : String(error)}`);
      }
    };

    initDatabase();

    // Cleanup on component unmount
    return () => {
      const closeDb = async () => {
        if (dbClientRef.current) {
          await dbClientRef.current.close();
          addLog('数据库连接已关闭');
        }
      };
      closeDb();
    };
  }, []);

  // Create users table
  const createUsersTable = async () => {
    if (!dbClientRef.current) return;
    
    try {
      const tableExists = await dbClientRef.current.isTableExists(tableName);
      
      if (!tableExists) {
        const createTableSQL = `
          CREATE TABLE IF NOT EXISTS ${tableName} (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            email TEXT,
            age INTEGER
          )
        `;
        
        await dbClientRef.current.executeRawQuery(createTableSQL);
        addLog(`创建表 ${tableName} 成功`);
      } else {
        addLog(`表 ${tableName} 已存在`);
      }
    } catch (error) {
      addLog(`创建表失败: ${error instanceof Error ? error.message : String(error)}`);
    }
  };

  // Add a sample user
  const addSampleUser = async () => {
    if (!dbClientRef.current) return;
    
    try {
      const user: User = {
        id: '', // Will be generated by the client
        name: `User ${Math.floor(Math.random() * 1000)}`,
        email: `user${Math.floor(Math.random() * 1000)}@example.com`,
        age: Math.floor(Math.random() * 80) + 18
      };
      
      const savedUser = await dbClientRef.current.create<User>(tableName, user);
      addLog(`添加用户成功: ${savedUser.name}`);
      
      // Refresh users list
      loadUsers();
    } catch (error) {
      addLog(`添加用户失败: ${error instanceof Error ? error.message : String(error)}`);
    }
  };

  // Load all users
  const loadUsers = async () => {
    if (!dbClientRef.current) return;
    
    try {
      const allUsers = await dbClientRef.current.findAll<User>(tableName);
      setUsers(allUsers);
      addLog(`加载了 ${allUsers.length} 个用户`);
    } catch (error) {
      addLog(`加载用户失败: ${error instanceof Error ? error.message : String(error)}`);
    }
  };

  // Delete a user
  const deleteUser = async (id: string) => {
    if (!dbClientRef.current) return;
    
    try {
      await dbClientRef.current.delete(tableName, id);
      addLog(`删除用户 ID: ${id} 成功`);
      
      // Refresh users list
      loadUsers();
    } catch (error) {
      addLog(`删除用户失败: ${error instanceof Error ? error.message : String(error)}`);
    }
  };

  // Clear all users
  const clearUsers = async () => {
    if (!dbClientRef.current) return;
    
    try {
      await dbClientRef.current.executeRawQuery(`DELETE FROM ${tableName}`);
      addLog('清空所有用户数据');
      
      // Refresh users list
      loadUsers();
    } catch (error) {
      addLog(`清空用户数据失败: ${error instanceof Error ? error.message : String(error)}`);
    }
  };

  // Helper function to add log messages
  const addLog = (message: string) => {
    setLog(prevLog => [...prevLog, `${new Date().toLocaleTimeString()}: ${message}`]);
  };

  return (
    <div className="p-4">
      <h1 className="text-2xl font-bold mb-4">SQLite 离线存储演示</h1>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <IonCard>
            <IonCardHeader>
              <IonCardTitle>数据操作</IonCardTitle>
            </IonCardHeader>
            <IonCardContent>
              <div className="flex flex-col space-y-2">
                <IonButton 
                  disabled={!isDbInitialized} 
                  onClick={addSampleUser}
                >
                  添加随机用户
                </IonButton>
                
                <IonButton 
                  disabled={!isDbInitialized} 
                  onClick={loadUsers}
                >
                  加载所有用户
                </IonButton>
                
                <IonButton 
                  disabled={!isDbInitialized} 
                  onClick={clearUsers}
                  color="danger"
                >
                  清空所有用户
                </IonButton>
              </div>
            </IonCardContent>
          </IonCard>
          
          <IonCard className="mt-4">
            <IonCardHeader>
              <IonCardTitle>用户列表</IonCardTitle>
            </IonCardHeader>
            <IonCardContent>
              {users.length === 0 ? (
                <p className="text-gray-500">暂无用户数据</p>
              ) : (
                <IonList>
                  {users.map(user => (
                    <IonItem key={user.id}>
                      <IonLabel>
                        <h2>{user.name}</h2>
                        <p>{user.email} | 年龄: {user.age}</p>
                      </IonLabel>
                      <IonButton 
                        slot="end" 
                        color="danger" 
                        onClick={() => deleteUser(user.id)}
                      >
                        删除
                      </IonButton>
                    </IonItem>
                  ))}
                </IonList>
              )}
            </IonCardContent>
          </IonCard>
        </div>
        
        <IonCard>
          <IonCardHeader>
            <IonCardTitle>操作日志</IonCardTitle>
          </IonCardHeader>
          <IonCardContent>
            <div className="bg-gray-100 p-3 rounded-md h-[500px] overflow-y-auto">
              {log.map((entry, index) => (
                <div key={index} className="mb-1">
                  <code>{entry}</code>
                </div>
              ))}
            </div>
          </IonCardContent>
        </IonCard>
      </div>
    </div>
  );
}