// client/config-keys.ts

/**
 * 客户端服务配置键
 * 集中管理所有与客户端服务相关的配置键
 */
export const CLIENT_KEYS = {
  // 客户端服务提供者类型
  NEXT_PUBLIC_CLIENT_PROVIDER: 'NEXT_PUBLIC_CLIENT_PROVIDER',
  CLIENT_ADAPTER: 'CLIENT_ADAPTER',
  
  // 客户端存储相关配置
  NEXT_PUBLIC_STORAGE_PREFIX: 'NEXT_PUBLIC_STORAGE_PREFIX',
  NEXT_PUBLIC_STORAGE_ENCRYPTION: 'NEXT_PUBLIC_STORAGE_ENCRYPTION',
  
  // 客户端功能特性开关
  NEXT_PUBLIC_CLIENT_FEATURES: 'NEXT_PUBLIC_CLIENT_FEATURES',
  
  // 客户端运行模式
  NEXT_PUBLIC_CLIENT_MODE: 'NEXT_PUBLIC_CLIENT_MODE',
};

/**
 * 客户端服务业务配置键
 * 集中管理所有与客户端业务功能相关的配置键
 */
export const CLIENT_BUSINESS_KEYS = {
  // 本地存储相关
  NEXT_PUBLIC_LOCAL_STORAGE_TYPE: 'NEXT_PUBLIC_LOCAL_STORAGE_TYPE',
  NEXT_PUBLIC_LOCAL_STORAGE_FEATURES: 'NEXT_PUBLIC_LOCAL_STORAGE_FEATURES',
  
  // 传感器相关
  NEXT_PUBLIC_SENSOR_TYPE: 'NEXT_PUBLIC_SENSOR_TYPE',
  NEXT_PUBLIC_SENSOR_FEATURES: 'NEXT_PUBLIC_SENSOR_FEATURES',
  
  // 通知相关
  NEXT_PUBLIC_NOTIFICATION_TYPE: 'NEXT_PUBLIC_NOTIFICATION_TYPE',
  NEXT_PUBLIC_NOTIFICATION_FEATURES: 'NEXT_PUBLIC_NOTIFICATION_FEATURES',
};