import { GrowthTaskPlanConfig } from "../member-growth-task.types";

export const mockGrowthTaskPlanConfig: GrowthTaskPlanConfig = {
  type: "rookie7",
  tasks: [
    {
      id: "task-1",
      day: 1,
      title: "完善个人资料",
      description: "完善头像、昵称、性别、年龄、兴趣等基础信息，提升个人吸引力。",
      exp: 50,
      reward: { type: "gift", value: "rose", desc: "奖励玫瑰*3" },
      ext: { feature: "profile" },
    },
    {
      id: "task-2",
      day: 2,
      title: "首次发起聊天",
      description: "与任意用户发起一次聊天，体验即时沟通。",
      exp: 30,
      reward: { type: "vip", value: 1, desc: "VIP体验1天" },
      ext: { feature: "messages" },
    },
    {
      id: "task-3",
      day: 3,
      title: "上传生活照片",
      description: "上传至少一张生活照，增加真实感。",
      exp: 40,
      reward: { type: "skin", value: "summer2025", desc: "解锁夏日皮肤" },
      ext: { feature: "profile" },
    },
    {
      id: "task-4",
      day: 4,
      title: "每日签到",
      description: "连续签到4天，保持活跃。",
      exp: 10,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "checkin" },
    },
    {
      id: "task-5",
      day: 5,
      title: "完成一次匹配",
      description: "通过系统推荐或主动喜欢完成一次匹配。",
      exp: 20,
      reward: { type: "gift", value: "chocolate", desc: "奖励巧克力*1" },
      ext: { feature: "matches", matchType: "system" },
    },
    {
      id: "task-6",
      day: 6,
      title: "点赞互动",
      description: "给3位用户点赞，积极参与社区互动。",
      exp: 15,
      reward: { type: "exp", value: 30, desc: "成长值+30" },
      ext: { feature: "like" },
    },
    {
      id: "task-7",
      day: 7,
      title: "连续活跃",
      description: "连续7天登录App，成为高活跃用户。",
      exp: 50,
      reward: { type: "badge", value: "rookie7", desc: "新手勋章" },
      ext: { feature: "auth" },
    },
    {
      id: "task-8",
      day: 8,
      title: "完善兴趣标签",
      description: "设置3个兴趣标签，提升个性化推荐效果。",
      exp: 20,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "profile" },
    },
    {
      id: "task-9",
      day: 9,
      title: "首次使用筛选",
      description: "使用筛选功能查找心仪对象。",
      exp: 15,
      reward: { type: "gift", value: "diamond", desc: "奖励钻石*1" },
      ext: { feature: "filter" },
    },
    {
      id: "task-10",
      day: 10,
      title: "参与问卷/测评",
      description: "完成一次官方问卷或兴趣测评，获得专属标签。",
      exp: 25,
      reward: { type: "badge", value: "quiz", desc: "测评达人徽章" },
      ext: { feature: "quiz" },
    },
    {
      id: "task-11",
      day: 11,
      title: "参与智能推荐匹配测试",
      description: "体验一次智能推荐（AI算法）匹配，协助优化推荐效果。",
      exp: 25,
      reward: { type: "exp", value: 30, desc: "成长值+30" },
      ext: { feature: "matches", matchType: "ai_recommend" },
    },
    {
      id: "task-12",
      day: 12,
      title: "参与兴趣标签匹配测试",
      description: "通过兴趣标签进行一次匹配，丰富标签数据。",
      exp: 20,
      reward: { type: "gift", value: "rose", desc: "奖励玫瑰*2" },
      ext: { feature: "matches", matchType: "tag_based" },
    },
    {
      id: "task-13",
      day: 13,
      title: "参与距离优先匹配测试",
      description: "完成一次基于距离的匹配，协助采集地理数据。",
      exp: 20,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "matches", matchType: "distance" },
    },
    {
      id: "task-14",
      day: 14,
      title: "参与活跃度优先匹配测试",
      description: "完成一次基于活跃度的匹配，提升平台活跃度数据。",
      exp: 20,
      reward: { type: "gift", value: "chocolate", desc: "奖励巧克力*1" },
      ext: { feature: "matches", matchType: "active" },
    },
    {
      id: "task-15",
      day: 15,
      title: "参与问卷型匹配测试",
      description: "完成一次问卷型匹配，完善用户画像。",
      exp: 30,
      reward: { type: "badge", value: "quiz", desc: "问卷达人徽章" },
      ext: { feature: "matches", matchType: "quiz" },
    },
  ],
  achievements: [
    {
      id: "achv-1",
      name: "新手毕业",
      condition: "完成全部新手任务，解锁全部功能。",
      icon: "/badges/rookie7.png",
      reward: { type: "vip", value: 3 },
    },
    {
      id: "achv-2",
      name: "社交达人",
      condition: "累计发起10次聊天。",
      icon: "/badges/social.png",
      reward: { type: "gift", value: "car" },
    },
    {
      id: "achv-3",
      name: "活跃之星",
      condition: "连续14天登录App。",
      icon: "/badges/active.png",
      reward: { type: "skin", value: "vip_gold" },
    },
    {
      id: "achv-4",
      name: "测试先锋",
      condition: "完成所有匹配算法测试任务。",
      icon: "/badges/tester.png",
      reward: { type: "exp", value: 100 },
    },
  ],
  startAt: "2025-04-21",
  updatedAt: "2025-04-21T16:18:00+08:00",
  updatedBy: "ops",
  metadata: { note: "任务深度关联多种匹配测试与核心功能，便于数据采集与算法优化" },
};
