import { GrowthTaskPlanConfig } from "../member-growth-task.types";

export const mockGrowthTaskPlanConfig30Days: GrowthTaskPlanConfig = {
  type: "rookie30",
  tasks: [
    // 1-7天：基础引导+核心功能体验
    {
      id: "task-1",
      day: 1,
      title: "完善个人资料",
      description: "完善头像、昵称、性别、兴趣等，提升个人吸引力。",
      exp: 50,
      reward: { type: "gift", value: "rose", desc: "奖励玫瑰*3" },
      ext: { feature: "profile" },
    },
    {
      id: "task-2",
      day: 2,
      title: "首次发起聊天",
      description: "与任意用户发起一次聊天，体验即时沟通。",
      exp: 30,
      reward: { type: "vip", value: 1, desc: "VIP体验1天" },
      ext: { feature: "messages" },
    },
    {
      id: "task-3",
      day: 3,
      title: "上传生活照片",
      description: "上传至少一张生活照，增加真实感。",
      exp: 40,
      reward: { type: "skin", value: "summer2025", desc: "解锁夏日皮肤" },
      ext: { feature: "profile" },
    },
    {
      id: "task-4",
      day: 4,
      title: "每日签到",
      description: "连续签到4天，保持活跃。",
      exp: 10,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "checkin" },
    },
    {
      id: "task-5",
      day: 5,
      title: "完成一次匹配",
      description: "通过系统推荐或主动喜欢完成一次匹配。",
      exp: 20,
      reward: { type: "gift", value: "chocolate", desc: "奖励巧克力*1" },
      ext: { feature: "matches", matchType: "system" },
    },
    {
      id: "task-6",
      day: 6,
      title: "点赞互动",
      description: "给3位用户点赞，积极参与社区互动。",
      exp: 15,
      reward: { type: "exp", value: 30, desc: "成长值+30" },
      ext: { feature: "like" },
    },
    {
      id: "task-7",
      day: 7,
      title: "连续活跃",
      description: "连续7天登录App，成为高活跃用户。",
      exp: 50,
      reward: { type: "badge", value: "rookie7", desc: "新手勋章" },
      ext: { feature: "auth" },
    },
    // 8-14天：进阶体验+社交扩展
    {
      id: "task-8",
      day: 8,
      title: "完善兴趣标签",
      description: "设置3个兴趣标签，提升个性化推荐效果。",
      exp: 20,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "profile" },
    },
    {
      id: "task-9",
      day: 9,
      title: "首次使用筛选",
      description: "使用筛选功能查找心仪对象。",
      exp: 15,
      reward: { type: "gift", value: "diamond", desc: "奖励钻石*1" },
      ext: { feature: "filter" },
    },
    {
      id: "task-10",
      day: 10,
      title: "参与问卷/测评",
      description: "完成一次官方问卷或兴趣测评，获得专属标签。",
      exp: 25,
      reward: { type: "badge", value: "quiz", desc: "测评达人徽章" },
      ext: { feature: "quiz" },
    },
    {
      id: "task-11",
      day: 11,
      title: "参与智能推荐匹配测试",
      description: "体验一次智能推荐（AI算法）匹配，协助优化推荐效果。",
      exp: 25,
      reward: { type: "exp", value: 30, desc: "成长值+30" },
      ext: { feature: "matches", matchType: "ai_recommend" },
    },
    {
      id: "task-12",
      day: 12,
      title: "参与兴趣标签匹配测试",
      description: "通过兴趣标签进行一次匹配，丰富标签数据。",
      exp: 20,
      reward: { type: "gift", value: "rose", desc: "奖励玫瑰*2" },
      ext: { feature: "matches", matchType: "tag_based" },
    },
    {
      id: "task-13",
      day: 13,
      title: "参与距离优先匹配测试",
      description: "完成一次基于距离的匹配，协助采集地理数据。",
      exp: 20,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "matches", matchType: "distance" },
    },
    {
      id: "task-14",
      day: 14,
      title: "参与活跃度优先匹配测试",
      description: "完成一次基于活跃度的匹配，提升平台活跃度数据。",
      exp: 20,
      reward: { type: "gift", value: "chocolate", desc: "奖励巧克力*1" },
      ext: { feature: "matches", matchType: "active" },
    },
    // 15-21天：好友互动+深度社交
    {
      id: "task-15",
      day: 15,
      title: "邀请好友注册",
      description: "邀请1位好友注册并完善资料。",
      exp: 40,
      reward: { type: "gift", value: "rose", desc: "奖励玫瑰*5" },
      ext: { feature: "invite" },
    },
    {
      id: "task-16",
      day: 16,
      title: "与好友互发消息",
      description: "与已添加的好友互发2条消息。",
      exp: 20,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "messages" },
    },
    {
      id: "task-17",
      day: 17,
      title: "赠送礼物",
      description: "向任意用户赠送1份虚拟礼物。",
      exp: 20,
      reward: { type: "gift", value: "rose", desc: "奖励玫瑰*2" },
      ext: { feature: "gift" },
    },
    {
      id: "task-18",
      day: 18,
      title: "收到礼物",
      description: "收到任意用户赠送的礼物。",
      exp: 20,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "gift" },
    },
    {
      id: "task-19",
      day: 19,
      title: "参与群聊/话题",
      description: "在群聊或话题区发言1次。",
      exp: 20,
      reward: { type: "badge", value: "topic", desc: "话题达人徽章" },
      ext: { feature: "topic" },
    },
    {
      id: "task-20",
      day: 20,
      title: "收藏心仪对象",
      description: "将1位用户加入心仪列表。",
      exp: 15,
      reward: { type: "exp", value: 15, desc: "成长值+15" },
      ext: { feature: "favorite" },
    },
    {
      id: "task-21",
      day: 21,
      title: "连续签到21天",
      description: "连续21天签到，成为签到达人。",
      exp: 50,
      reward: { type: "badge", value: "checkin21", desc: "签到达人徽章" },
      ext: { feature: "checkin" },
    },
    // 22-30天：深度活跃+平台生态
    {
      id: "task-22",
      day: 22,
      title: "首次体验会员功能",
      description: "体验一次会员专属功能（如超级喜欢、隐身等）。",
      exp: 25,
      reward: { type: "vip", value: 1, desc: "VIP体验1天" },
      ext: { feature: "vip" },
    },
    {
      id: "task-23",
      day: 23,
      title: "完善个人签名",
      description: "设置一句有趣的个人签名。",
      exp: 10,
      reward: { type: "exp", value: 10, desc: "成长值+10" },
      ext: { feature: "profile" },
    },
    {
      id: "task-24",
      day: 24,
      title: "参与官方活动",
      description: "报名参与一次官方线上活动。",
      exp: 20,
      reward: { type: "badge", value: "event", desc: "活动参与徽章" },
      ext: { feature: "event" },
    },
    {
      id: "task-25",
      day: 25,
      title: "反馈建议",
      description: "提交一次产品建议或反馈。",
      exp: 20,
      reward: { type: "exp", value: 20, desc: "成长值+20" },
      ext: { feature: "feedback" },
    },
    {
      id: "task-26",
      day: 26,
      title: "连续活跃26天",
      description: "连续26天登录App，成为深度用户。",
      exp: 40,
      reward: { type: "skin", value: "vip_gold", desc: "解锁VIP金色皮肤" },
      ext: { feature: "auth" },
    },
    {
      id: "task-27",
      day: 27,
      title: "首次举报不良行为",
      description: "成功举报1次不良行为，维护社区健康。",
      exp: 20,
      reward: { type: "badge", value: "report", desc: "守护者徽章" },
      ext: { feature: "report" },
    },
    {
      id: "task-28",
      day: 28,
      title: "参与平台生态问卷",
      description: "完成一次平台生态相关问卷，助力平台优化。",
      exp: 25,
      reward: { type: "exp", value: 25, desc: "成长值+25" },
      ext: { feature: "quiz" },
    },
    {
      id: "task-29",
      day: 29,
      title: "连续点赞互动",
      description: "连续7天每日点赞1次。",
      exp: 20,
      reward: { type: "gift", value: "diamond", desc: "奖励钻石*2" },
      ext: { feature: "like" },
    },
    {
      id: "task-30",
      day: 30,
      title: "新手毕业典礼",
      description: "完成全部30天新手任务，领取毕业大礼包。",
      exp: 100,
      reward: { type: "vip", value: 7, desc: "VIP体验7天+专属礼包" },
      ext: { feature: "event" },
    },
  ],
  achievements: [
    {
      id: "achv-1",
      name: "新手毕业",
      condition: "完成全部30天新手任务，解锁全部功能。",
      icon: "/badges/rookie30.png",
      reward: { type: "vip", value: 7 },
    },
    {
      id: "achv-2",
      name: "活跃达人",
      condition: "连续30天登录App。",
      icon: "/badges/active30.png",
      reward: { type: "skin", value: "vip_gold" },
    },
    {
      id: "achv-3",
      name: "社交之星",
      condition: "累计发起30次聊天。",
      icon: "/badges/social30.png",
      reward: { type: "gift", value: "car" },
    },
    {
      id: "achv-4",
      name: "生态守护者",
      condition: "成功举报3次不良行为。",
      icon: "/badges/report.png",
      reward: { type: "badge", value: "report" },
    },
  ],
  startAt: "2025-04-21",
  updatedAt: "2025-04-21T16:20:00+08:00",
  updatedBy: "ops",
  metadata: { note: "参考手游新手活动，7天/30天双loop丰富任务与成就体系，覆盖核心功能与生态建设" },
};
